#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    items=`ls /mnt/c/Users/Admin/Pictures/anime`
    selected=`echo "$items" | fzf`
fi

# /mnt/c/Users/Admin/Pictures/anime
powershell.exe wallpaper.pyw $selected
